name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - init-project
    tags:
      - "cr*"

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: meeting-ai-agent
  REGION: asia-northeast1
  IMAGE: $REGION-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Delete old image
        continue-on-error: true
        run: gcloud artifacts docker images delete ${{ env.IMAGE }} --quiet

      - name: Build a docker image
        run: docker build -t ${{ env.IMAGE }} apps/cloudrun

      - name: Push the docker image
        run: docker push ${{ env.IMAGE }}

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated
